### ISSUE TITLE
Submit host state

### ISSUE THREAD

**Issue by fhaferkorn** [Mizzrym/php_send_nsca#11]
In current version it isn't implemented to submit any passiv host state. Could you please implement or explain why it isn't possible. 
Thx

**Comment by nueaf** [comment]
For now no one else has had the need for passive host states, which is why it is not done yet. 
You are welcome to implement it and make a pull request.

**Comment by Mizzrym** [comment]
The goal of this entire program is to provide a PHP implementation of send_nsca, so your PHP application can send checks to your monitoring system without using plattform dependend shell escapes to the send_nsca c program. So the goal is to avoid the operating system all together, not checking for its health. That's why there are no host checks. It's an entirely different thing to be handled by the monitoring system or the operating systems, virtualisation, whatever, but not by a web application/service. Not the mention that i don't see a way for PHP to reliably check a hosts health without using shell escapes - in which case you're better off with bash anyway. 

If you really want to have it i could implement it for you (once i've finished work for today). But please, double check first if PHP is the right tool for whatever problem you're trying to solve currently. 
Remember: "The chief cause of problems is solutions". 

HTH.

**Comment by fhaferkorn** [comment]
Thanks for your recent replies.
@Mizzrym I understand your attitude to it and can confirm it. Your are right. But in my case, I use my monitoring system not for checking any machine states, but for having a great kind-of alarm system including all psoitive side effects. 
So I definitly need a method for submitting passive "check result" for a host via the nsca logic.

**Comment by Mizzrym** [comment]
@fhaferkorn Well, IF nsca understands the host check when the service is just left blank this will be an easy fix. If it doesn't and one needs to build an entirely different package things might get complicated. 
Anyway, my workday just started. I'll check this again in the evening and see what i can do.

**Comment by Mizzrym** [comment]
It already worked. Just send an empty string for service and nsca will interpret it as passive host check. 
I added two additional methods to avoid confusion.

**Comment by fhaferkorn** [comment]
Nice. Thanks

**Comment by Mizzrym** [comment]
You're welcome. 
And thanks for the star :)
